### PR TITLE
Do not update permissions or attributes if other share fields gets updated

### PR DESCRIPTION
**Pull request by mrow4a**
Update share can update any field in share interface separately. This MR ensures that attributes get updated only if attribute or permission fields got updated.

Important note: this change is independent on oc10 release, it is nice to have to prevent issues in the future.

@phil-davis

### CODE REVIEW

**Comment by mrow4a** [comment]
@LinneyS just to mention, this merge wont be critical, but would be good to have. We made sure compatibility is preserved even with expiration.

**Comment by LinneyS** [comment]
Hi @mrow4a 
I cherry picked your commits
thanks
Sorry for the long wait

**Comment by jnweiger** [comment]
I understand everything was done ca 2 months back here. But we still don't see a new release in our marketplace.
@LinneyS could you please check on your side, if the release process got stuck somewhere?
image

**Comment by jnweiger** [comment]
Version 4.2.1 arrived in https://marketplace.owncloud.com/apps/onlyoffice
Thanks for the release!

**Pull request closed without merging**
