### PR TITLE
Brazilian Portuguese translation added to l10n folder

### PR DESCRIPTION
**Pull request by tavinus**
#### New files
- `l10n/pt_BR.js`
- `l10n/pt_BR.json`

This is running in our production server already.
I have revised the translation many times, but sorry if I still have missed something.

Note: Not sure how the plural stuff at the end of each file works. I didn't touch that.

Cheers!
Gus

### CODE REVIEW

**Comment by LinneyS** [comment]
It's great!
Can you create a pull request to develop branch?

**Comment by tavinus** [comment]
Ok, it is there: https://github.com/ONLYOFFICE/onlyoffice-owncloud/pull/144

Had to `git reset --hard upstream/develop` because I the merging created some mess on commits.
It should be fine like this though (just adding the 2 files to your last commit on develop and without extra/repeated commits).

Cheers!
Gus

**Comment by tavinus** [comment]
oh shit.. pushed the wrong branch..

**Comment by ShockwaveNN** [comment]
Close as duplicate of https://github.com/ONLYOFFICE/onlyoffice-owncloud/pull/144

**Pull request closed without merging**
