### PR TITLE
add forcesave option

### LINKED ISSUE #116: Write to own-/nextcloud on save and/or interval of X seconds/minutes
Currently onlyoffice writes a changed file to owncoud10-30 seconds after ALL editors closed the file. 

Is there a possibility that onlyoffice triggers this write every X seconds (if a change occurred)? This would avoid sync problems if someone forgets to close the file, which is a problem if another client is changing the file with the owncloud desktop/mobile client.

### PR DESCRIPTION
**Pull request by fmkaiser**
Fixes #116 

This allows for manual saves to ownCloud. For autosave default.json on the Document Server would need to be adjusted as well.

The question for me is whether this should be a config flag or hardcoded as the default.

At least in our case the current behaviour - document is saved only when closed by the last user - lead to quite a bit of confusion until we found the forcesave option.

### CODE REVIEW

**Comment by LinneyS** [comment]
This fix will have a very bad effect on **co-editing**.
Scenario:
- open the file for editing,
- press Save,
- open the file for editing by the second user.
Result:
users do not have collaborative editing.

It is because of this problem that _forcesave_ is not implemented.

**Comment by fmkaiser** [comment]
@LinneyS: That's unfortunate.
I'm guessing that in this case the second user is essentially opening a different document, which is why collaborative editing does not work?
Is there any way to reload the first user's document/session after the forcesave?

Otherwise I guess we'll need to drop this pull request.

**Comment by LinneyS** [comment]
We are developing changes for Document Server to get this result.

**Comment by duckhawk** [comment]
If it not possible to forcesave, can I somehow force onlyoffice to save all documents from cache? (for example, if I needs to reboot server)

**Comment by ibnpetr** [comment]
@duckhawk 

> can I somehow force onlyoffice to save all documents from cache? (for example, if I needs to reboot server)


`bash documentserver-prepare4shutdown.sh`

**Comment by pitchum** [comment]
Hello, any update on this?
We recently hit this issue and it took us some time to understand what was going on.

If implementing forcesave is not possible, at least it would be useful to have some UI hints making it obvious to users that the document they are currently viewing is not saved in nextcloud/owncloud.

**Comment by harry91** [comment]
> 
> 
> We are developing changes for Document Server to get this result.

It's been two years...

**Comment by rasos** [comment]
@LinneyS if OO would auto or force save and another user would open the intermediate version from nextcloud then the OO document server should be made aware of the fact that the same document is being opened (and not open another editing session). Is this feasible?

**Comment by LinneyS** [comment]
Hi all!
Try _Keep intermediate versions when editing_ in settings in v6.0.1

**Pull request closed without merging**
