### PR TITLE
Introduce controller for loading the web-extension js bundle

### PR DESCRIPTION
**Pull request by kulmann**
This PR adds a controller for loading the js bundle for the ownCloud Web extension via ownCloud instead of fetching it via the webserver.

Also updated the `README.md` to reflect the new config for ownCloud web's `config.json`.

### CODE REVIEW

**Comment by ShockwaveNN** [comment]
> (not ready yet)

If this not ready yet -you can convert PR to draft PR - this linke should be somehere in right menu of this page

**Comment by kulmann** [comment]
> > (not ready yet)
> 
> If this not ready yet -you can convert PR to draft PR - this linke should be somehere in right menu of this page

Did that, thanks 👍 

Should I target `master` or `develop` with this PR?

**Comment by ShockwaveNN** [comment]
@kulmann Sorry, I'm not a maintainer of this particular repo, but juding by feature PR like this - `develop` should be the target

**Comment by kulmann** [comment]
This PR is ready for review now

**Review by Antipkin-A — APPROVED** [review]

**Comment by LinneyS** [comment]
Hi @kulmann 
What is the advantage of this solution?

**Comment by kulmann** [comment]
> Hi @kulmann
> What is the advantage of this solution?

The admin doesn't need additional config for loading the js bundle through the webserver, but instead it is solved with the already existing config for webserver+oc10. Two other aspects:
- admin doesn't need to look if onlyoffice lies in the folder `custom`, `apps-external`, etc
- hosting doesn't expose the internal folder structure, but exposes the js file via the unified `index.php/apps` route.

**Pull request merged**
